/**
 * useAllotmentCareLogs Hook
 *
 * Care logs and harvest tracking for permanent areas.
 * Handles care log CRUD and harvest totals.
 *
 * Writes go through `mutate(fn)` against the SyncedStore proxy (ADR 027;
 * legacy `setData` branch removed in Step 5).
 */

'use client'

import { useCallback } from 'react'
import {
  AllotmentData,
  CareLogEntry,
  NewCareLogEntry,
  AreaSeason,
} from '@/types/unified-allotment'
import {
  getCareLogsForArea,
  getAllCareLogsForArea,
  getHarvestTotal,
} from '@/services/allotment-storage'
import { generateId } from '@/lib/utils'
import type { MutateFn } from './useAllotmentData'
import { assignDefined, withoutUndefined } from '@/lib/yjs/allotment-yjs'

// ============ HOOK TYPES ============

export interface UseAllotmentCareLogsProps {
  data: AllotmentData | null
  mutate: MutateFn
  selectedYear: number
}

export interface UseAllotmentCareLogsReturn {
  addCareLog: (areaId: string, entry: NewCareLogEntry) => string
  updateCareLog: (areaId: string, entryId: string, updates: Partial<Omit<CareLogEntry, 'id'>>) => void
  removeCareLog: (areaId: string, entryId: string) => void
  getCareLogs: (areaId: string) => CareLogEntry[]
  getAllCareLogs: (areaId: string) => Array<{ year: number; entry: CareLogEntry }>
  logHarvest: (areaId: string, quantity: number, unit: string, date?: string) => string
  getHarvestTotal: (areaId: string) => { quantity: number; unit: string } | null
}

// ============ HOOK IMPLEMENTATION ============

export function useAllotmentCareLogs({
  data,
  mutate,
  selectedYear,
}: UseAllotmentCareLogsProps): UseAllotmentCareLogsReturn {

  const addCareLogData = useCallback((areaId: string, entry: NewCareLogEntry): string => {
    if (!data) return ''

    // ID has to be computed up front so we can return it synchronously
    // — the mutate callback runs inside the Yjs transaction but the
    // ID is generated by `generateId` outside it (the legacy path
    // does the same, computing the ID inside `addCareLogEntry`).
    const id = generateId()
    mutate(store => {
      const season = store.seasons.find(s => s.year === selectedYear)
      if (!season) return
      const now = new Date().toISOString()

      let areaSeason = season.areas.find(a => a.areaId === areaId)
      if (!areaSeason) {
        const fresh: AreaSeason = withoutUndefined({
          areaId,
          plantings: [],
          careLogs: [],
        })
        season.areas.push(fresh)
        areaSeason = season.areas[season.areas.length - 1]
      }

      if (!areaSeason.careLogs) areaSeason.careLogs = []
      const newEntry: CareLogEntry = withoutUndefined({ ...entry, id })
      areaSeason.careLogs.push(newEntry)
      season.updatedAt = now
      store.meta.updatedAt = now
    })
    return id
  }, [data, selectedYear, mutate])

  const updateCareLogData = useCallback((
    areaId: string,
    entryId: string,
    updates: Partial<Omit<CareLogEntry, 'id'>>
  ) => {
    if (!data) return

    mutate(store => {
      const season = store.seasons.find(s => s.year === selectedYear)
      if (!season) return
      const areaSeason = season.areas.find(a => a.areaId === areaId)
      if (!areaSeason?.careLogs) return
      const log = areaSeason.careLogs.find(l => l.id === entryId)
      if (!log) return
      const now = new Date().toISOString()
      assignDefined(log as unknown as Record<string, unknown>, updates as Record<string, unknown>)
      season.updatedAt = now
      store.meta.updatedAt = now
    })
  }, [data, selectedYear, mutate])

  const removeCareLogData = useCallback((areaId: string, entryId: string) => {
    if (!data) return

    mutate(store => {
      const season = store.seasons.find(s => s.year === selectedYear)
      if (!season) return
      const areaSeason = season.areas.find(a => a.areaId === areaId)
      if (!areaSeason?.careLogs) return
      const idx = areaSeason.careLogs.findIndex(l => l.id === entryId)
      if (idx === -1) return
      areaSeason.careLogs.splice(idx, 1)
      const now = new Date().toISOString()
      season.updatedAt = now
      store.meta.updatedAt = now
    })
  }, [data, selectedYear, mutate])

  const getCareLogsData = useCallback((areaId: string): CareLogEntry[] => {
    if (!data) return []
    return getCareLogsForArea(data, selectedYear, areaId)
  }, [data, selectedYear])

  const getAllCareLogsData = useCallback((areaId: string): Array<{ year: number; entry: CareLogEntry }> => {
    if (!data) return []
    return getAllCareLogsForArea(data, areaId)
  }, [data])

  const logHarvestData = useCallback((
    areaId: string,
    quantity: number,
    unit: string,
    date?: string
  ): string => {
    if (!data) return ''

    // logHarvest is a convenience wrapper around addCareLogEntry.
    const id = generateId()
    mutate(store => {
      const season = store.seasons.find(s => s.year === selectedYear)
      if (!season) return
      const now = new Date().toISOString()
      let areaSeason = season.areas.find(a => a.areaId === areaId)
      if (!areaSeason) {
        const fresh: AreaSeason = withoutUndefined({
          areaId,
          plantings: [],
          careLogs: [],
        })
        season.areas.push(fresh)
        areaSeason = season.areas[season.areas.length - 1]
      }
      if (!areaSeason.careLogs) areaSeason.careLogs = []
      const entry: CareLogEntry = withoutUndefined<CareLogEntry>({
        id,
        type: 'harvest',
        date: date || new Date().toISOString().split('T')[0],
        quantity,
        unit,
      })
      areaSeason.careLogs.push(entry)
      season.updatedAt = now
      store.meta.updatedAt = now
    })
    return id
  }, [data, selectedYear, mutate])

  const getHarvestTotalData = useCallback((areaId: string): { quantity: number; unit: string } | null => {
    if (!data) return null
    return getHarvestTotal(data, selectedYear, areaId)
  }, [data, selectedYear])

  return {
    addCareLog: addCareLogData,
    updateCareLog: updateCareLogData,
    removeCareLog: removeCareLogData,
    getCareLogs: getCareLogsData,
    getAllCareLogs: getAllCareLogsData,
    logHarvest: logHarvestData,
    getHarvestTotal: getHarvestTotalData,
  }
}
