/**
 * useAllotmentCareLogs Hook
 *
 * Care logs and harvest tracking for permanent areas.
 * Handles care log CRUD and harvest totals.
 *
 * Two-branch methods (ADR 027 Step 3, PR-B): see useAllotmentAreas for
 * the convention. The Yjs branch mutates the targeted `AreaSeason`'s
 * `careLogs` array in place.
 */

'use client'

import { useCallback } from 'react'
import {
  AllotmentData,
  CareLogEntry,
  NewCareLogEntry,
  AreaSeason,
} from '@/types/unified-allotment'
import {
  addCareLogEntry as storageAddCareLogEntry,
  updateCareLogEntry as storageUpdateCareLogEntry,
  removeCareLogEntry as storageRemoveCareLogEntry,
  getCareLogsForArea,
  getAllCareLogsForArea,
  logHarvest as storageLogHarvest,
  getHarvestTotal,
} from '@/services/allotment-storage'
import { generateId } from '@/lib/utils'
import { USE_YJS_STORAGE } from '@/config/release-visibility'
import type { MutateFn } from './useAllotmentData'
import { assignDefined, withoutUndefined } from './yjs-helpers'

// ============ HOOK TYPES ============

export interface UseAllotmentCareLogsProps {
  data: AllotmentData | null
  setData: (data: AllotmentData | ((prev: AllotmentData | null) => AllotmentData | null)) => void
  mutate: MutateFn
  selectedYear: number
}

export interface UseAllotmentCareLogsReturn {
  addCareLog: (areaId: string, entry: NewCareLogEntry) => string
  updateCareLog: (areaId: string, entryId: string, updates: Partial<Omit<CareLogEntry, 'id'>>) => void
  removeCareLog: (areaId: string, entryId: string) => void
  getCareLogs: (areaId: string) => CareLogEntry[]
  getAllCareLogs: (areaId: string) => Array<{ year: number; entry: CareLogEntry }>
  logHarvest: (areaId: string, quantity: number, unit: string, date?: string) => string
  getHarvestTotal: (areaId: string) => { quantity: number; unit: string } | null
}

// ============ HOOK IMPLEMENTATION ============

export function useAllotmentCareLogs({
  data,
  setData,
  mutate,
  selectedYear,
}: UseAllotmentCareLogsProps): UseAllotmentCareLogsReturn {

  const addCareLogData = useCallback((areaId: string, entry: NewCareLogEntry): string => {
    if (!data) return ''

    if (USE_YJS_STORAGE) {
      // ID has to be computed up front so we can return it synchronously
      // — the mutate callback runs inside the Yjs transaction but the
      // ID is generated by `generateId` outside it (the legacy path
      // does the same, computing the ID inside `addCareLogEntry`).
      const id = generateId()
      mutate(store => {
        const season = store.seasons.find(s => s.year === selectedYear)
        if (!season) return
        const now = new Date().toISOString()

        let areaSeason = season.areas.find(a => a.areaId === areaId)
        if (!areaSeason) {
          const fresh: AreaSeason = withoutUndefined({
            areaId,
            plantings: [],
            careLogs: [],
          })
          season.areas.push(fresh)
          areaSeason = season.areas[season.areas.length - 1]
        }

        if (!areaSeason.careLogs) areaSeason.careLogs = []
        const newEntry: CareLogEntry = withoutUndefined({ ...entry, id })
        areaSeason.careLogs.push(newEntry)
        season.updatedAt = now
        store.meta.updatedAt = now
      })
      return id
    }

    const result = storageAddCareLogEntry(data, selectedYear, areaId, entry)
    setData(result.data)
    return result.entryId
  }, [data, selectedYear, setData, mutate])

  const updateCareLogData = useCallback((
    areaId: string,
    entryId: string,
    updates: Partial<Omit<CareLogEntry, 'id'>>
  ) => {
    if (!data) return

    if (USE_YJS_STORAGE) {
      mutate(store => {
        const season = store.seasons.find(s => s.year === selectedYear)
        if (!season) return
        const areaSeason = season.areas.find(a => a.areaId === areaId)
        if (!areaSeason?.careLogs) return
        const log = areaSeason.careLogs.find(l => l.id === entryId)
        if (!log) return
        const now = new Date().toISOString()
        assignDefined(log as unknown as Record<string, unknown>, updates as Record<string, unknown>)
        season.updatedAt = now
        store.meta.updatedAt = now
      })
      return
    }

    setData(storageUpdateCareLogEntry(data, selectedYear, areaId, entryId, updates))
  }, [data, selectedYear, setData, mutate])

  const removeCareLogData = useCallback((areaId: string, entryId: string) => {
    if (!data) return

    if (USE_YJS_STORAGE) {
      mutate(store => {
        const season = store.seasons.find(s => s.year === selectedYear)
        if (!season) return
        const areaSeason = season.areas.find(a => a.areaId === areaId)
        if (!areaSeason?.careLogs) return
        const idx = areaSeason.careLogs.findIndex(l => l.id === entryId)
        if (idx === -1) return
        areaSeason.careLogs.splice(idx, 1)
        const now = new Date().toISOString()
        season.updatedAt = now
        store.meta.updatedAt = now
      })
      return
    }

    setData(storageRemoveCareLogEntry(data, selectedYear, areaId, entryId))
  }, [data, selectedYear, setData, mutate])

  const getCareLogsData = useCallback((areaId: string): CareLogEntry[] => {
    if (!data) return []
    return getCareLogsForArea(data, selectedYear, areaId)
  }, [data, selectedYear])

  const getAllCareLogsData = useCallback((areaId: string): Array<{ year: number; entry: CareLogEntry }> => {
    if (!data) return []
    return getAllCareLogsForArea(data, areaId)
  }, [data])

  const logHarvestData = useCallback((
    areaId: string,
    quantity: number,
    unit: string,
    date?: string
  ): string => {
    if (!data) return ''

    if (USE_YJS_STORAGE) {
      // logHarvest is a convenience wrapper around addCareLogEntry on
      // the legacy path. Mirror that by routing through the same Yjs
      // branch — keeps the two implementations textually close.
      const id = generateId()
      mutate(store => {
        const season = store.seasons.find(s => s.year === selectedYear)
        if (!season) return
        const now = new Date().toISOString()
        let areaSeason = season.areas.find(a => a.areaId === areaId)
        if (!areaSeason) {
          const fresh: AreaSeason = withoutUndefined({
            areaId,
            plantings: [],
            careLogs: [],
          })
          season.areas.push(fresh)
          areaSeason = season.areas[season.areas.length - 1]
        }
        if (!areaSeason.careLogs) areaSeason.careLogs = []
        const entry: CareLogEntry = withoutUndefined<CareLogEntry>({
          id,
          type: 'harvest',
          date: date || new Date().toISOString().split('T')[0],
          quantity,
          unit,
        })
        areaSeason.careLogs.push(entry)
        season.updatedAt = now
        store.meta.updatedAt = now
      })
      return id
    }

    const result = storageLogHarvest(data, selectedYear, areaId, quantity, unit, date)
    setData(result.data)
    return result.entryId
  }, [data, selectedYear, setData, mutate])

  const getHarvestTotalData = useCallback((areaId: string): { quantity: number; unit: string } | null => {
    if (!data) return null
    return getHarvestTotal(data, selectedYear, areaId)
  }, [data, selectedYear])

  return {
    addCareLog: addCareLogData,
    updateCareLog: updateCareLogData,
    removeCareLog: removeCareLogData,
    getCareLogs: getCareLogsData,
    getAllCareLogs: getAllCareLogsData,
    logHarvest: logHarvestData,
    getHarvestTotal: getHarvestTotalData,
  }
}
